# Generated by Django 5.1.1 on 2024-09-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychoshield', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id_creador',
        ),
    ]
