# Generated by Django 5.1.1 on 2024-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoshield', '0005_user_is_active_user_is_admin_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='edad',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='test',
            name='educacion',
            field=models.CharField(choices=[('inicial_completa', 'Inicial completa'), ('inicial_incompleta', 'Inicial incompleta'), ('primaria_completa', 'Primaria completa'), ('primaria_incompleta', 'Primaria incompleta'), ('secundaria_completa', 'Secundaria completa'), ('secundaria_incompleta', 'Secundaria incompleta'), ('tecnica_completa', 'Técnica completa'), ('tecnica_incompleta', 'Técnica incompleta'), ('universitaria_completa', 'Universitaria completa'), ('universitaria_incompleta', 'Universitaria incompleta'), ('maestria_completa', 'Maestría completa'), ('maestria_incompleta', 'Maestría incompleta'), ('doctorado_completo', 'Doctorado completo'), ('doctorado_incompleto', 'Doctorado incompleto')], default='primaria_completa', max_length=30),
        ),
        migrations.AddField(
            model_name='test',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('viudo', 'Viudo/a'), ('separado', 'Separado/a'), ('divorciado', 'Divorciado/a')], default='soltero', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='ocupacion',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('no_decir', 'Prefiero no decirlo')], default='no_decir', max_length=10),
        ),
    ]
