# Generated by Django 5.1.1 on 2024-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoshield', '0006_test_edad_test_educacion_test_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='sintomatologia_presentada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
